### ISSUE TITLE
Add a command to get a tty in a docker image with all the NFS mounts etc

### ISSUE THREAD

**Issue by ihodes** [hammerlab/secotrec#54]
This would be insanely useful for debugging, and doing this by hand is no fun!

**Comment by smondet** [comment]
This puts you on the Ketrew-server's container:

```
secotrec-gke  dc exec kserver bash
```

(`dc` is an alias for `docker-compose`)

Keeping the issue open because creating a fresh separate container with desired properties would still be useful for messing around.
